### ISSUE TITLE
Setup frontend hosting

### ISSUE THREAD

**Issue by christoff-linde** [SchizzY/next-month-web#14]
### Description

It might be a good idea to setup hosting for the frontend part of the project.

The `tauri` part does not require hosting, as it will be used to build a installable version of the app. See #13 for related setup task

### Task List

- [ ] Setup hosting (most likely Vercel)

### Resources
_For reference, can use any of the following repos:_
- [GitLight](https://github.com/colinlienard/gitlight)
- [SpaceDrive](https://github.com/spacedriveapp/spacedrive)

**Comment by SchizzY** [comment]
Going to close this issue, now switched to next and thus moved over to vercel as well
